### ISSUE TITLE
Add methods to programatically resize/crop/rotate or change quality of the image.

### ISSUE THREAD

**Issue by meznaric** [meznaric/react-native-image-cropping#1]
2 people on Facebook requested some extra features.

Proposed methods:

``` javascript
ReactNativeImageCropping.resize(imageUri, newWidth, newHeight);
ReactNativeImageCropping.crop(imageUri, x, y, width, height);
ReactNativeImageCropping.rotate(imageUri, 90); //Degrees should be 90,180, 270 or should we support all?
ReactNativeImageCropping.changeQuality(imageUri, 90); //Quality from 1-100 similar to what JPEG
ReactNativeImageCropping.moveToAlbum(imageUri, albumName);
ReactNativeImageCropping.moveToDocuments(imageUri, filename); //Is this needed?
```

Idea is that you should always be able to pass in original image object and you will always get back image with `image.uri` set to path to image in NSTemporaryDirectory. User should then decide where he wants to move it using `moveToDocuments` or `moveToAlbum`.

Any thoughts?

**Comment by skizzo** [comment]
That sounds perfect, but wouldn't it be more flexible to return **only** the URI (simple String) of the processed file instead of an actual image object, or did I get that wrong?
I assume that
- the `image` parameter would be a URI to the image itself?
- it would work with JPEGs only (no problem for me)?

The `moveToAlbum(..)` and `moveToDocuments(..)` functions are (imho) not necessary, this could easily be accomplished by [react-native-fs](https://github.com/johanneslumpe/react-native-fs) which works for iOS **and** Android.

**Comment by meznaric** [comment]
@skizzo Thanks, I wasn't aware of  [react-native-fs](https://github.com/johanneslumpe/react-native-fs). I will skip last two points then.

I want that all of these methods return the same image object as the one you get when you require image: `require('./Solids.jpg')`. Image parameter could indeed be just the URI. I will update my first comment to reflect the changes.

**Comment by geirman** [comment]
doesn't look like react-native-fs allows you to create albums. I'm still unclear how an album is created exactly. I suspect it's simply creating a new folder and placing it in a particular place, in which case react-native-fs would probably work, but again... not sure.

**Comment by meznaric** [comment]
@geirman You have to use one of the frameworks provided by apple to save to album either ALAssetLibrary (deprecated) or Photos(recommended). 

Since I already built this piece of functionality in another library I will port it over to this one.

**Comment by meznaric** [comment]
Unfortunately, I still haven't had time to work on that. If you just need cropping you can do it using `ImageEdit` as suggested by @sibelius on #3 .

https://github.com/facebook/react-native/blob/0.28-stable/Libraries/Image/ImageEditor.js

**Comment by meznaric** [comment]
I am not going to have time to build new features. I will try to maintain this library and merge any useful PRs.
