### ISSUE TITLE
how to pass Image path not as url

### ISSUE THREAD

**Issue by sarangan** [meznaric/react-native-image-cropping#14]
Hi, this library is really great, it works well with http urls but when i try to pass the camera image path like assets-library or disk path it gave me error. is there any workaround for this issue? or i am doing something wrong?  thank you.

**Comment by sarangan** [comment]
Okay I fixed it by changing UImage to read from path. thanks

**Comment by hasnainali3** [comment]
@sarangan can share you code, what you did. Having same issue.

Thanks.

**Comment by sarangan** [comment]
@hasnainali3 https://github.com/sarangan/react-native-image-cropper-ios
