### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by sibelius** [meznaric/react-native-image-cropping#3]

**Comment by meznaric** [comment]
Would love to help. But I do not have Android device nor the time at the moment. I will happily merge pull requests if anyone wants to contribute.

**Comment by superandrew213** [comment]
Any third party libs for android that match the iOS one?

**Comment by sibelius** [comment]
It is possible to crop an image using react native API itself, there is no need for a bridge for that

**Comment by superandrew213** [comment]
@sibelius yes you can use [ImageEditor](https://github.com/facebook/react-native/blob/0.28-stable/Libraries/Image/ImageEditor.js)
