### ISSUE TITLE
Add method to set max/min zoom in the crop box

### ISSUE THREAD

**Issue by alexanderludvigs** [meznaric/react-native-image-cropping#4]
Could you add a method that also defines the max zoom, something like: 

.cropImageWithUrlAndAspectAnd**MaxZoom**(imageUrl, aspectRatio, **MaxZoomWidth**, **MaxZoomHeight**)

the idea is that MaxZoomWidth and MaxZoomHeight would be the same as the width and height in the image object  _(image = { uri, width, height })_  that is returned in the then() block after cropping has finished.

Example: When I zoom in with two fingers until I can't zoom any furter and click "Done" the width and height values that are returned in the image object are 24. I would like to set MaxZoomWidth and Height to f.x. 300.

Great work by the way!

**Comment by meznaric** [comment]
Hey @alexanderludvigs I have no time to develop new features but I will try to maintain the library. I will happily merge a PR if you manage to extend it.
