### ISSUE TITLE
No visibile @interface for 'RCTImageLoader' declares the...

### ISSUE THREAD

**Issue by ghost** [meznaric/react-native-image-cropping#8]
During compile time I am getting the following error:

```
No visibile @interface for 'RCTImageLoader' declares the selector 'loadImageWithTag:callback:'
```

Versions:

```
React Native: 0.32.0
```

**Comment by meznaric** [comment]
@ChristianTucker thanks for reporting this. I have time later Today and will get the PR #7 merged in. That should fix the issue.
