### ISSUE TITLE
_reactNative.NativeModules.ReactNativeImageCropping.cropImageWithUrl

### ISSUE THREAD

**Issue by Woodswu** [meznaric/react-native-image-cropping#9]
i had error question in xcode 8 

loadImageWithURLRequest:imageUrlrequest  this function is not undefine

**Comment by Woodswu** [comment]
```
[self.bridge.imageLoader loadImageWithURLRequest:imageUrlrequest callback:^(NSError *error, UIImage *image) {
    if(error) reject(@"100", @"Failed to load image", error);
    if(image) {
        [self handleImageLoad:image];
    }
}];
```

**Comment by Woodswu** [comment]
Is it because of apple's latest update caused this mistake

**Comment by meznaric** [comment]
@wuzh3838 Are you saying this is happening only on latest iOS? Do you have any url to breaking changes?

**Comment by Woodswu** [comment]
yes,Before the update operation is normal

**Comment by wuzh3838** [comment]
![Uploading image.png…]()

**Comment by Woodswu** [comment]
When I compile errors
this is  report error:
/node_modules/react-native-image-cropping/ReactNativeImageCropping.m:60:30: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithURLRequest:callback:'

node_modules/react-native-image-cropping/ReactNativeImageCropping.m:80:30: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithURLRequest:callback:'

this is my package.json
  "dependencies": {
    "apsl-react-native-button": "^3.0.0",
    "react": "^15.0.2",
    "react-native": "^0.26.0",
    "react-native-audio": "^2.0.0",
    "react-native-busy-indicator": "^1.0.9",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-floating-label-text-input": "0.0.9",
    "react-native-image-cropping": "^1.0.0",
    "react-native-image-zoom": "^0.31.0",
    "react-native-storage": "^0.1.4"
  }

xcode:
       xcode 8
